require("config.ui.colorscheme")
require("config.ui.dashboard-nvim")
require("config.ui.galaxyline")
require("config.ui.gitsigns")
require("config.ui.nvim-bufferline")
require("config.ui.nvim-web-devicons")
require("config.ui.indent-blankline")
