require('config.lsp.nvim-lsp-settings')
require('config.lsp.python-ls')
require('config.lsp.efm-general-ls')
require('config.lsp.diagnostics')
require('config.lsp.nvim-compe')
-- require('config.lsp.lspkind')
require('config.lsp.nvim-lightbulb')
