# Taps
tap "koekeishiya/formulae"
tap "osx-cross/arm"
tap "osx-cross/avr"
tap "qmk/qmk"

# Formulae
brew "ack"
brew "basedpyright"
brew "bat"
brew "chafa"
brew "coreutils"
brew "direnv"
brew "entr"
brew "eslint_d"
brew "fd"
brew "findutils"
brew "fzf"
brew "gh"
brew "git"
brew "git-extras"
brew "git-lfs"
brew "glab"
brew "gnu-sed"
brew "gnupg"
brew "grep"
brew "hadolint"
brew "hyperfine"
brew "icu4c@76"
brew "imagemagick"
brew "jq"
brew "koekeishiya/formulae/skhd"
brew "lua"
brew "lua-language-server"
brew "luarocks"
brew "markdownlint-cli2"
brew "moreutils"
brew "neovim"
brew "openssh"
brew "openssl@3"
brew "pandoc"
brew "php"
brew "pipx"
brew "pkgconf"
brew "pngpaste"
brew "prettierd"
brew "qmk/qmk/qmk"
brew "rename"
brew "ripgrep"
brew "screen"
brew "selene"
brew "shellcheck"
brew "shfmt"
brew "ssh-copy-id"
brew "starship"
brew "stylua"
brew "task"
brew "tmux"
brew "tree"
brew "tree-sitter"
brew "tree-sitter-cli"
brew "vim"
brew "vscode-langservers-extracted"
brew "vtsls"
brew "wget"
brew "xz"
brew "zlib"
brew "zsh"

# Casks
cask "font-jetbrains-mono"
cask "font-symbols-only-nerd-font"

# Local (machine-specific, not committed)
local_brewfile = File.expand_path("Brewfile.local", __dir__)
eval(File.read(local_brewfile)) if File.exist?(local_brewfile)

# vim:ft=ruby
