require('config.autopairs')
require('config.coc')
require('config.colorizer')
require('config.colorscheme')
require('config.comment')
-- require('config.completion')
require('config.fugitive')
require('config.gitsigns')
require('config.indent_blankline')
-- require('config.lspkind')
-- require('config.neoformat')
require('config.nvim_tree')
require('config.nvim_web_devicons')
require('config.statusline')
require('config.telescope')
require('config.treesitter')
