local map = require("my.utils").map_factory({ silent = true })

map("n", "<Leader>dc", function()
    require("dap").continue()
end, { desc = "Continue" })
map("n", "<Leader>dC", function()
    require("my.plugins.nvim-dap.utils").reload_continue()
end, { desc = "Reload continue" })
map("n", "<Leader>dj", function()
    require("dap").step_over()
end, { desc = "Step over" })
map("n", "<Leader>dl", function()
    require("dap").step_into()
end, { desc = "Step into" })
map("n", "<Leader>dk", function()
    require("dap").step_out()
end, { desc = "Step out" })
map("n", "<Leader>dt", function()
    require("dap").toggle_breakpoint()
end, { desc = "Toggle breakpoint" })
map("n", "<Leader>dbc", function()
    require("dap").set_breakpoint(vim.fn.input("Breakpoint condition: "))
end, { desc = "Set conditional breakpoint" })
map("n", "<Leader>dbl", function()
    require("dap").set_breakpoint(nil, nil, vim.fn.input("Log point message: "))
end, { desc = "Set breakpoint with log" })
map("n", "<Leader>dbe", function()
    require("dap").set_exception_breakpoints({ "all" })
end, { desc = "Set exception breakpoint" })
map(
    "n",
    "<Leader>dr",
    ':lua require("dap").repl.open({}, "vsplit")<CR><C-w>l',
    { desc = "Open DAP REPL" }
)
map("n", "<Leader>dR", function()
    require("dap").run_last()
end, { desc = "Run last" })
map("n", "<Leader>d?", function()
    require("dap.ui.variables").scopes()
end, { desc = "Variable scopes" })
map("n", "<Leader>di", function()
    require("dap.ui.variables").hover(function()
        return vim.fn.expand("<cexpr>")
    end)
end, { desc = "Variable info" })
map("v", "<Leader>di", function()
    require("dap.ui.variables").visual_hover()
end, { desc = "Variable info" })
map("n", "<Leader>dh", function()
    require("dap.ui.widgets").hover()
end, { desc = "Widget hover" })
map("n", "<Leader>df", function()
    local widgets = require("dap.ui.widgets")
    widgets.centered_float(widgets.scopes)
end, { desc = "Widget float" })

local ok, wk = pcall(require, "which-key")
if ok then
    wk.register({ d = { name = "+dap", b = { name = "+breakpoint" } } }, { prefix = "<leader>" })
    wk.register({ d = { name = "+dap" } }, { mode = "v", prefix = "<leader>" })
end
