require("plugins.config.ui.dashboard-nvim")
require("plugins.config.ui.galaxyline")
require("plugins.config.ui.gitsigns")
require("plugins.config.ui.nvim-bufferline")
require("plugins.config.ui.nvim-web-devicons")
require("plugins.config.ui.indent-blankline")
