vim.filetype.add({
    extension = {
        gql = "graphql",
        graphql = "graphql",
        graphqls = "graphql",
    },
    filename = {
        [".ansible-lint"] = "yaml",
        [".gitmessage"] = "gitcommit",
        [".markdownlintrc"] = "json",
        [".pylintrc"] = "conf",
        [".tmux.conf.local"] = "tmux",
        [".zprofile"] = "zsh",
        [".zshenv"] = "zsh",
        [".zshrc"] = "zsh",
        ["gitconfig"] = "gitconfig",
        ["gitignore"] = "gitignore",
        ["gitmessage"] = "gitcommit",
        ["kitty.conf"] = "conf",
        ["pylintrc"] = "conf",
        ["zprofile"] = "zsh",
        ["zshenv"] = "zsh",
        ["zshrc"] = "zsh",
    },
    pattern = {
        -- gitconfig with suffix (e.g. .gitconfig.local)
        ["%.gitconfig%..*"] = "gitconfig",
        -- zsh files with suffix (e.g. .zshrc.local, .zshenv.local, .zprofile.local)
        ["%.zshrc%..*"] = "zsh",
        ["%.zshenv%..*"] = "zsh",
        ["%.zprofile%..*"] = "zsh",
        -- zshenv.shim
        ["zshenv%..*"] = "zsh",
        -- ansible
        [".*/ansible/.*%.yml"] = "yaml.ansible",
        [".*/ansible/.*%.yaml"] = "yaml.ansible",
        [".*/playbooks/.*%.yml"] = "yaml.ansible",
        [".*/playbooks/.*%.yaml"] = "yaml.ansible",
        [".*/roles/.*%.yml"] = "yaml.ansible",
        [".*/roles/.*%.yaml"] = "yaml.ansible",
        [".*/handlers/.*%.yml"] = "yaml.ansible",
        [".*/handlers/.*%.yaml"] = "yaml.ansible",
        [".*/tasks/.*%.yml"] = "yaml.ansible",
        [".*/tasks/.*%.yaml"] = "yaml.ansible",
        -- docker compose
        ["docker%-compose%.yml"] = "yaml.docker-compose",
        ["docker%-compose%.yaml"] = "yaml.docker-compose",
        ["docker%-compose%..*%.yml"] = "yaml.docker-compose",
        ["docker%-compose%..*%.yaml"] = "yaml.docker-compose",
        ["compose%.yml"] = "yaml.docker-compose",
        ["compose%.yaml"] = "yaml.docker-compose",
        ["compose%..*%.yml"] = "yaml.docker-compose",
        ["compose%..*%.yaml"] = "yaml.docker-compose",
    },
})
