require("my.config.utility.rooter")
require("my.config.utility.markdown-preview")
-- require("my.config.utility.fterm")
require("my.config.utility.kommentary")
require("my.config.utility.whichkey")
require("my.config.utility.vim-pydocstring")
require("my.config.utility.nvim-autopairs")
